### ISSUE TITLE
Error running python manage.py loaddata datas.json

### ISSUE THREAD

**Issue by Gensight** [suhailvs/django-schools#11]
When I run: 
python manage.py loaddata datas.json
I am getting the error:
django.db.utils.IntegrityError: Problem installing fixtures: The row in table 'classroom_quiz' with primary key '1' has an invalid foreign key: classroom_quiz.subject_id contains a value '5' that does not have a corresponding value in classroom_subject.id.

I have looked at the datas.json file and it looks good. Not sure where to look now.

**Comment by suhailvs** [comment]
i think that error may due to exisiting data in database. if you run it in a fresh database will solve the problem.

**Comment by Gensight** [comment]
I added values to the classroom_subject table and it's working. The database was new when I got the error. Maybe an error in datas.json. 
All is good now and I can play with your site. Thank you!
